### ISSUE TITLE
the checkpoint of MobileNetV3 Large

### ISSUE THREAD

**Issue by SmileTAT** [jacobswan1/SEED#11]
Thanks for the great work.
Do you have any plans to release a checkpoint of MobileNetV3 Large using ResNet-50x2* distilled?

**Comment by jacobswan1** [comment]
Hi there, thanks for asking. Unfortunately it has been too long and I don't keep the checkpoint anymore. It would be great if you can reproduce the MobileNetV3's result and welcome to submit a pull request to merge for sharing.
