### ISSUE TITLE
TSV dataset for ImageNet-1k？

### ISSUE THREAD

**Issue by mZhenz** [jacobswan1/SEED#5]
Hi, it seems like there isn't any description about TSV dataset preparation for ImageNet-1k in MoCov2 repository. 
Would you update the dataset preparation part?
Thanks a lot.

**Comment by mZhenz** [comment]
I change it into original datasets.ImageFolder().

**Comment by deropty** [comment]
> I change it into original datasets.ImageFolder().

Can you provide the details about how to prepare the TSV dataset?  Or how to use ImageFolder()?

Thanks very much!
