### ISSUE TITLE
Is the training hyper-parameters of ResNet-18 with moco consist with ResNet-50?

### ISSUE THREAD

**Issue by liming-ai** [jacobswan1/SEED#7]
Hi @jacobswan1 

When you train ResNet-18 with standard moco v2, did you make any changes to the training hyper-parameters or strategies? Or did you just use the hyper-parameters of ResNet-50?

**Comment by jacobswan1** [comment]
Hi Ming, 

When I train the ResNet18, I followed most settings and hyper-parameters in MoCo-V2. I don't quite remember I tuned any parameters in particular but maybe there are optimal parameters that could lead to a stronger ResNet18 by MoCov2.

**Comment by liming-ai** [comment]
> Hi Ming,
> 
> When I train the ResNet18, I followed most settings and hyper-parameters in MoCo-V2. I don't quite remember I tuned any parameters in particular but maybe there are optimal parameters that could lead to a stronger ResNet18 by MoCov2.

Thanks a lot for your reply~
