### ISSUE TITLE
Cannot reproduce the same mAP on COCO with the backbone of ResNet18-C4 based on Mask RCNN

### ISSUE THREAD

**Issue by Rene-SP** [jacobswan1/SEED#9]
Table 2 of your paper reports the mAP of COCO object detection with the backbone of ResNet18-C4 based on Mask RCNN. Without knowledge distillation, the mAP of bounding box is 35.0 given 2x optimization setting. But my implementation only gives 27.94. I wonder which part I missed results in this sub-optimal performance.

**Comment by jacobswan1** [comment]
For the COCO detection-related question, please refer to Kaiming's MoCo repository: https://github.com/facebookresearch/moco
